# Generated by Django 4.2.24 on 2025-11-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_client_departament_order_section_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
